#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 1
bspc config window_gap 6
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_padding 18
bspc config focused_border_color "#dc322f"
bspc config normal_border_color "#111111"

panel dzen2 &
#! /bin/sh

#bspc monitor -d 1 2 3 4 5 6 7 8 9 0
#
#bspc config border_width        2
#bspc config window_gap          7
#bspc config split_ratio         0.52
#bspc config borderless_monocle  true
#bspc config gapless_monocle     true
#
#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#panel &
